version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  motor_dynamic:
    build: .
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_URL=amqps://burraqtq:yFx0LDD76FrrDRFLhd2Wk_R68YfwhG00@cow.rmq2.cloudamqp.com/burraqtq
    volumes:
      - ./data:/app/data

  forecasting-service:
    build: ../forecasting-service
    depends_on:
      - rabbitmq
      - motor_dynamic
    environment:
      - RABBITMQ_URL=amqps://burraqtq:yFx0LDD76FrrDRFLhd2Wk_R68YfwhG00@cow.rmq2.cloudamqp.com/burraqtq
